apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit
  namespace: logging
  labels:
    app: fluentbit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit
  namespace: logging
  labels:
    app: fluentbit
rules:
- apiGroups: [""]
  resources:
  - pods
  - namespaces
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentbit
  namespace: logging
  labels:
    app: fluentbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentbit
subjects:
- kind: ServiceAccount
  name: fluentbit
  namespace: logging
