apiVersion: batch/v1
kind: Job
metadata:
  name: package-check-repeat
spec:
  completions: 3
  template:
    spec:
      containers:
      - name: package-check-repeat
        image: ubuntu
        command: ["dpkg-query", "-l"]
      restartPolicy: Never
